SE/config/routes.rb
SE::Application.routes.draw do



  root :to => 'pages#home'
  match 'utilidad', :to => 'pages#utilidad'
  match 'indicador', :to => 'pages#antecedentes'
  match 'aliados', :to => 'pages#participantes'
  match 'acerca', :to => 'pages#acerca'
  match 'administradores', :to => 'pages#administradores'
  match 'fuentes', :to => 'pages#fuentes'
  get "reportes/ranking"
  post "reportes/new"

  resources :reportes
  resources :users, :only => [:show, :index, :edit, :update]
  resources :sessions, :only => [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match "remember", :to => 'sessions#remember'
  match "ruperto", :to => 'sessions#ruperto'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', :to => 'errors#error_404'
  end



end

SE/app/models/comparacion.rb
class Comparacion < Db3
  set_table_name :'IndicadorConComparacionesItems'
  set_primary_key :'dane'
end

SE/app/models/indicadorr.rb
class Indicadorr < Db3
  set_table_name :'IndicadorEducacionR'
  set_primary_key :'dane'

end

SE/app/controllers/reportes_controller.rb
# encoding = utf-8
class ReportesController < ApplicationController

  before_filter :authenticate, :only => [:ranking , :show, :index]

  def index
      @title = "Reportes"
      colegios = Indicador.find(:all, :order => 'nombre ASC')
      # trae los colegios para desplegarlos es la lista, eliminando los 11 colegios no incluidos
      @colegios = colegios.delete_if{|x| x.dane ==  105001005380 or
                                          x.dane == 305001022640 or
                                          x.dane == 105001025771 or
                                          x.dane == 105001025763 or
                                          x.dane == 105001026131 or
                                          x.dane == 105001025992 or
                                          x.dane == 105001025798 or
                                          x.dane == 105001025984 or
                                          x.dane == 105001001881 or
                                          x.dane == 105001026000 or
                                          x.dane == 105001019143
                                    }


      respond_to do |format|
      format.html              #/alumnos/index
      format.json {render :json => @colegios}
    end
  end

  def show
    @title = "Reporte Individual"
    params[:option_select]
    @ambientes = Merge.find(params[:id])
    @rendimientos = Indicador.find(params[:id])
    @info_col = Directoria.find(params[:id])
    @multivariados = Multivariado.find(params[:id])
    @multivariadob = Multivariadob.find(params[:id])
    @cluster = Cluster.find(params[:id])
    @varcolegio = Varcolegio.find(params[:id])
    @pares = Cluster.find_all_by_Cluster(@cluster.Cluster)
    @bonus5 = Bonus5.find(params[:id])
    @bonus11 = Bonus11.find(params[:id])
    @taprob = Taprob.find(params[:id])
    @consolidado = []
    Multivariado.all.each {|resul| @consolidado << resul.IndicadorEducacion.to_f}
    @comparaciones = Comparacion.find(params[:id])
    @educacionr = Indicadorr.find(params[:id])
    @posiciones = [Multivariadob.all(:order => "IndicadorEducacion DESC"),
                   Multivariadob.all(:order => "IndicadorBonus DESC"),
                   Cluster.find_all_by_Cluster(@cluster.Cluster, :order => "IndicadorEducacion DESC"),
                   Cluster.find_all_by_Cluster(@cluster.Cluster, :order => "IndicadorBonus DESC"),
                   params[:id]]
    respond_to do |format|
       format.html # show.html.erb
       format.json  { render :json => @rendimientos }

     end

  end

  def new
    if params[:option_select].blank?
      redirect_to reportes_path, :alert => "Debe seleccionar una institución educativa"
    else
      id = params[:option_select]
      redirect_to "/reportes/#{id}"
    end
  end

  def ranking
    @title = "Ranking"
    if current_user.admin?
      @ranking = Multivariadob.all(:order => "IndicadorEducacion DESC")
      @rankingb = Multivariadob.all(:order => "IndicadorBonus DESC")
    else
      @ranking = Multivariadob.all(:order => "indicador DESC", :limit => 20)
      @rankingb = Multivariadob.all(:order => "IndicadorBonus DESC", :limit => 20)
    end

  end



  private

  def authenticate
   	deny_access unless signed_in?
  end






end

SE/app/helpers/reportes_helper.rb
# coding = UTF-8
module ReportesHelper


  def current_ie_name
          nombre = @nombre..split(' ')

  end

  def bonus
    @left = 0
    @right = 0
    if @rendimientos.bonus_total11.nil?
      @left = 0
    else
      @left = @rendimientos.bonus_total11
    end


    if@rendimientos.bonus_total5.nil?
      @right = 0
    else
      @right = @rendimientos.bonus_total5
    end
    (@left.to_i + @right.to_i)/4
  end

  def total
    @totales.ambiente_escolar.round(2) + @totales.rendimiento.round(2) + @totales.progreso.round(2)
  end

  def totalbonus
    total + bonus
  end
  def grade_ambiente(n)
        if n <= 18.95
          "E"
          elsif n <= 19.64
            "D"
          elsif n <= 20.24
            "C"
          elsif n <= 20.80
            "B"
          else
            "A"
        end

  end

  def grade_rendimiento(n)
    if n <= 14.22
       "E"
        elsif n <= 15.88
          "D"
        elsif n <= 16.22
           "C"
        elsif n <= 16.60
           "B"
        else
           "A"
     end
  end

  def grade_progreso(n)
    if n <= 2.24
       "E"
        elsif n <= 6.38
           "D"
        elsif n <= 7.44
           "C"
        elsif n <= 8.70
           "B"
        else
           "A"
    end

  end
  def nombre_correc(nombre)
    nombre = nombre.gsub('Ñ','ñ')
    nombre = nombre.gsub('Ó','ó')
    nombre = nombre.gsub('Í','í')
    nombre = nombre.gsub('Á','á')
    nombre = nombre.gsub('É','é')
  end

  def nombre_comp(nombre)
    nombre = nombre.gsub('Inst Educ','IE')
    nombre = nombre.gsub('Ñ','ñ')
    nombre = nombre.gsub('Cent Educ', 'CE')


  end

  def grade_total(n)
    if n <= 38.24
        "E"
    elsif n <= 40.87
        "D"
    elsif n <= 43.07
        "C"
    elsif n <= 46.48
        "B"
    elsif n >= 46.49
        "A"
    end
  end

  def verbose(word)
      if word.blank?
        "No Registra"
      else
        word
      end

  end
  def verbose_progreso(word)
    if word.blank?
      "No Registra"
    else
      "#{word.to_f.round(2)} "
    end
  end

  def verbosesim(word)
    if word.blank?
      "No Registra"
    else
      "#{word.to_f.round(2)}% "
    end

  end

  def verbosecal(word)
    if word.blank?
      "No Registra"
    else
      "#{(word.to_f.round(4) * 100).round(3)}%"
    end

  end

  def jornada(completa,manana,tarde,noche)
    jornada = ""
    if completa == "X"
      jornada = "Completa"
    end
    if manana.eql? "X"
      jornada = "#{jornada} Mañana"
    end
    if tarde.eql? "X"
      jornada = "#{jornada} Tarde"
    end
    if noche == "X"
      jornada = "#{jornada} Noche"
    end

    jornada
  end

  def categoria(categoria)
    case categoria.to_i
      when 1 then
        "Muy inferior"
      when 2 then
        "Inferior"
      when 3 then
        "Bajo"
      when 4 then
        "Medio"
      when 5 then
        "Alto"
      when 6 then
        "Superior"
      when 7 then
        "Muy superior"
    else
       "No Registra"
    end
  end

  def calificacion_ciudad(arr)
    resul = Hash.new
    resul[:A],resul[:B],resul[:C],resul[:D],resul[:E] = 0,0,0,0,0
    arr.each {|indicador| if grade_total(indicador) == "A"
                           resul[:A] +=1
                          elsif grade_total(indicador)== "B"
                            resul[:B] +=1
                          elsif grade_total(indicador)== "C"
                            resul[:C] +=1
                          elsif grade_total(indicador)== "D"
                            resul[:D] +=1
                          elsif grade_total(indicador)== "E"
                            resul[:E] +=1
                          end

              }
    resul


  end


  def percent(number, top)
    ((number.to_f * 100 )/top).round(2)
  end

  def posicion(arr, id)
    posicion = 0
    arr.each do |resultado|
      posicion += 1
      break if resultado.dane.to_s.eql? id

    end
    posicion

  end

  def comparar_ancho(metod)
    resultado = eval("@comparaciones"+"."+metod)
    if resultado.blank?
      "0%"
    else
      "#{resultado}%"
    end

  end

  def comparar_valor(metod)
    resultado = eval("@comparaciones"+"."+metod)
    if resultado.blank?
      " "
    else
      "#{resultado}%"
    end
  end


end

SE/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-32806011-1']);
      _gaq.push(['_trackPageview']);

      (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  </script>

</head>

    <body>



        <div id="header">
         <div id ="nav">
            <div class="name">
                <%= link_to(image_tag("HFull.png"),root_path) %>
            </div>
            <div class="bar">
                     <ul>
                       <% if signed_in? %>
                          <li><%=link_to current_user_name, current_user	  %></li>
                       <%end %>
                       <li><%=link_to "Inicio",root_path %></li>

                       <% if signed_in? %>
                            <li><%=link_to "Reportes", reportes_path %></li>
                        <% end %>
                           <% if signed_in? %>
                             <li><%= link_to "Salir", signout_path %></li>
                        <% else %>
                             <li><%= link_to "Ingresar", signin_path %></li>
                        <% end %>
                     </ul>
            </div>
         </div>
        </div>

        <div id = "content">
          <div id="big">
          	<% flash.each do |key, value| %>
	            <div class="flash <%= key %>"><%= value.capitalize %></div>
	        <%  end %>
            <h1 style="margin: auto; text-align: center;">Sistema de Medición de la Calidad de las Instituciones Educativas de Medellín</h1>
            <hr>
            <br>
            <br>
	        <%= yield %>
          </div>
          <div class="ajustar"></div>
          <br>
        </div>



        <div id="footer" style="clear: both; min-height: 320px">

            <div class="float-left ">
                <div class="module">
                    <p class="header">Información</p>
                    <ul style="margin: 0px 0px 0px 0px;" class="links">
                        <li><%=link_to "Administradores del Sistema", "/administradores" %></li>
                        <li><%=link_to "Aliados Estratégicos", "/aliados" %></li>
                      <li><%=link_to "Más acerca del Sistema de Medición de la Calidad de la Educación", "/acerca"%></li>
                        <!--<li><%=link_to "Antecedentes", "#" %></li>-->
                        <li><%= link_to "Fuentes de información del Sistema", "/fuentes" %></li>
                        <li><%= link_to "Indicador Multidimensional de la Calidad Educativa", "/indicador" %></li>
                        <li><%= link_to "Utilidad del Sistema", "/utilidad" %></li>
                    </ul>
                </div>
            </div>

            <div class="float-left">
                <div class="module">
                    <p class="header">Contacto</p>
                    <p>Laboratorio de Calidad Educativa</p>
                    <p>Secretaría de Educación de Medellín</p>
                    <p>Carrera 52 No. 44B – 17. Edificio Carré, Oficina 208</p>
                    <p>Tel&eacute;fono: <strong>(57+4) 514 82 46</strong></p>
                    <p>Email:<strong><a href="mailto:laboratorio.educacion@medellin.gov.co?subject=SIMCIE">laboratorio.educacion@medellin.gov.co</a></strong></p>
                    <p>Medellín, Antioquia, Colombia</p>
                </div>
            </div>
            <!--
            <div class="float-left ">
                <div class="module">
                    <p class="header">Medios Sociales</p>

                </div>
            </div>
            -->
          <div class="ajustar" style="min-height: 20px; clear: both;" >&nbsp;</div>
        </div>


        <p style="clear: both;" id="copyright">© 2012 Software diseñado y elaborado por la Universidad EAFIT, Medellín-Colombia. Derechos reservados Alcaldía de Medellín.</p>
    </body>
</html>

SE/app/views/pages/acerca.html.erb
    <div class="acerca">
      <h2 style="text-align: center;">Más acerca del Sistema de Medición de la Calidad de la Educación</h2>
      <br>
      <br>
      <h3>Origen</h3>
      <p>El Sistema de Medición de la Calidad de las Instituciones Educativas de la Ciudad de
      Medellín (SIMCIE-Medellín) es un proyecto liderado por la Secretaría de Educación
      de Medellín por medio de su Laboratorio de la Calidad de la Educación, instancia que
      tiene como misión ser un banco de datos y de indicadores y desarrollar y promover la
      construcción de estudios técnicos. En su construcción participó la Universidad Eafit de
      Medellín.
      </p>
      <h3>Definición</h3>
      <p>El Sistema de Medición es una herramienta de seguimiento y evaluación del servicio
      educativo que prestan las IE del Municipio, constituyéndose como un importante
      insumo de información para la toma de decisiones y para el diseño de estrategias y
      acciones pertinentes en pro del mejoramiento de la calidad del sistema educativo de
      Medellín.
      </p>
      <p>
      En este orden de ideas, con el SIMCIE-Medellín es posible identificar las fortalezas y
      debilidades de cada institución educativa, en su ambiente escolar de aprendizaje, el
      rendimiento y progreso académico de sus estudiantes, facultando así a las autoridades
      educativas y a las mismas instituciones para hacer correctivos si son necesarios y
      fortalecer y promover las virtudes.
      </p>
      <h3>Objetivos</h3>
      <ul>
        <li>Servir de herramienta de seguimiento y evaluación de la calidad del sistema
          educativo del Municipio y de cada institución.</li>
        <li>Facilitar la identificación de fortalezas y debilidades en calidad de cada institución
          educativa, específicamente en ambiente escolar y rendimiento y progreso
          académico de sus estudiantes</li>
        <li>Facultar a las autoridades educativas y a las mismas instituciones para la
          realización de correctivos pertinentes en el tema de calidad.</li>

        <li>Servir de insumo de información y toma de decisiones para la comunidad educativa
          (padres de familia, estudiantes, profesores, etc.)</li>
      </ul>
      <h3>Acceso al Sistema</h3>
      <p>El Sistema de Medición se encuentra montado en una plataforma flexible y
      multiusuario en la web, de tal manera que toda la comunidad educativa y la sociedad
      en general, puede acceder a ésta desde cualquier computador en el mundo con acceso
      a internet, ingresando con un usuario y contraseña.
      </p>
      <h3>Reportes del Sistema</h3>
      <p>En la plataforma del Sistema los usuarios que ingresen con su login y contraseña
      podrán acceder a distintos reportes agregados y por institución. Uno de ellos son
      los ranking de instituciones, que muestra en forma resumida, los resultados de
      cada institución Estos son informes técnicos que presentan información general
      y específica de cada institución educativa, siendo una «radiografía» del estado
      actual en que se encuentran la calidad educativa de la institución (y su avance) y las
      dimensiones que se consideran la determinan. La obtención de este diagnóstico se
      logra gracias al diseño y estimación de un Indicador Multidimensional de la Calidad de
      la Educación (IMCE).
      </p>
    </div>

SE/app/views/pages/antecedentes.html.erb
<h2 style="text-align: center;">Indicador multidimensional de calidad</h2>
<br>
<br>


<h3>Definición</h3>
<p>
    El Sistema de Medición estima un puntaje total denominado Indicador
    Multidimensional de la Calidad de la Educación (IMCE) permitiendo la comparación
    de una institución educativa con todas las IE de la ciudad y con aquellas con
    características similares. Para su construcción se han asumido tres dimensiones
    que se consideran determinan la calidad del sistema educativo como tal y de cada
    institución que lo forma.
</p>

<h3>Dimensiones determinantes de la calidad de la educación</h3>
    <p>La calidad de la educación depende o es determinada por varias dimensiones o
        variables. El Sistema de Medición ha considerado las siguientes:
    </p>
    <ol>
     <li>Ambiente Escolar de Aprendizaje</li>
     <li>Rendimiento Académico</li>
     <li>Progreso Académico</li>
    </ol>

<h3>Dimensión 1: Ambiente Escolar de Aprendizaje</h3>
    <p>
        Esta dimensión provee información sobre la forma específica en que se relacionan y
        se comunican los miembros de una institución educativa, como también la manera en
        que la misma involucra a los actores en el proceso de aprendizaje de los estudiantes.
    </p>
    <p>
        Es de resaltar que toda la comunidad educativa contribuye a la determinación de
        estos factores relacionales, comunicativos y motivacionales, que según la UNESCO
        juegan un papel crucial en el rendimiento escolar en Latinoamérica. Es decir, se ha
        observado que muchos de los problemas educativos existentes no están relacionados
        necesariamente con la instrucción o la infraestructura, sino con factores contextuales,
        organizativos y de relaciones personales que afectan los resultados educativos finales.
    </p>
    <p>
        Es así como, para poder construir una idea general del ambiente escolar de cada IE,
        se decidió diseñar y aplicar 3 instrumentos o encuestas de percepción que preguntan
        a los estudiantes, docentes y profesores sobre cuatro categorías o componentes de
        factores que condicionan el ambiente escolar: “Las Expectativas Académicas”, “la
        Participación”, “la Comunicación” y “la Seguridad y el Respeto”. Lo que intentan medir
        estas categorías se muestra en el siguiente cuadro.
    </p>
    <table border=1 cellspacing=0 cellpadding=2 >
      <tr>
        <td>CATEGORÍAS</td>
        <td>¿Que miden?</td>
      </tr>
      <tr>
        <td>EXPECTATIVAS ACADÉMICAS</td>
        <td>Nivel de motivación que el colegio brinda para cumplir con
          éxito la formación de los estudiantes a través de objetivos
          académicos rigurosos y coherentes
        </td>
      </tr>
      <tr>
        <td>COMUNICACIÓN</td>
        <td>Percepción frente al nivel de información que el colegio
          debe brindar acerca de los objetivos educativos y de su
          progreso con respecto a los resultados académicos de los
          alumnos
        </td>
      </tr>
      <tr>
        <td>PARTICIPACIÓN
          (COMPROMISO)
        </td>
        <td>Qué tan motivados se sienten los estudiantes con relación a
          su proceso de aprendizaje
        </td>
      </tr>
      <tr>
        <td>SEGURIDAD Y
          RESPETO
        </td>
        <td>Percepción frente a la seguridad física y emocional que
          ofrece el colegio, la cual es indispensable en todo proceso
          de aprendizaje</td>
      </tr>

    </table>


<h3>Dimensión 2: Rendimiento Académico</h3>
    <p>
        La segunda dimensión, el “Rendimiento Académico”, captura información sobre el
        nivel académico general de los estudiantes de cada institución educativa en distintos
        años, empleando los resultados agregados de las pruebas Saber 5, 9 y 11 del ICFES en
        las áreas de lenguaje y matemáticas, y las tasas de aprobación y extra-edad.
    </p>
    <p>
        Los resultados (puntajes) en las pruebas del ICFES se consideran como unas medidas
        permiten aproximarse a la estimación de la calidad de la educación. Dado que los
        resultados en las Pruebas Saber son individuales (a nivel de estudiantes), estos se
        agregaron a nivel de institución utilizando la medida estadística de la mediana de
        puntajes en cada área del conocimiento considerada.
    </p>

<h3>Dimensión 3: Progreso Académico</h3>
    <p>
        Esta dimensión registra el avance o retroceso en el rendimiento académico de
        cada institución educativa por medio de la captura de la variación existente en los
        resultados (puntajes) agregados de la institución en las pruebas Saber 5, 9 y 11 del
        ICFES en las áreas de lenguaje y matemáticas.
    </p>
    <p>
        Dado que las pruebas Saber del ICFES no son las mismas año a año (preguntas
        distintas, énfasis diferente, etc.), para usar simultáneamente pruebas de años distintos
        se deben “homogeneizar”, permitiendo así su comparabilidad. Una forma de hacerlo
        es transformando los resultados agregados (mediana del puntaje por institución) en
        percentiles, lo que permite establecer posiciones bien sea en los estudiantes y/o en
        las instituciones. En este orden de ideas, la variación en el rendimiento académico se
        registra en forma de percentiles.
    </p>
<h3>Bonificación</h3>
    <p>
        Una cuarta variable se ha considerado denominada “Bonus o Bonificación”, construida
        con el fin de reconocer la mayor dedicación y esfuerzo que deben realizar varias
        de las IE oficiales (incluidas las de contratación o cobertura) para poder lograr que
        un porcentaje importante de su población estudiantil logre elevar su rendimiento
        y progreso académico, dado que las condiciones socioeconómicas de los alumnos
        son restrictivas. Diferentes variables socioeconómicas y de entorno del colegio se
        emplean para poder identificar esta población y asignar un crédito adicional o premio
        al trabajo realizado por las IE que atienden población vulnerable (específicamente
        estudiantes de estratos bajos). Esta variable, que no se considera una dimensión como
        tal, se construye a partir de las bases de datos de Olimpiadas del Conocimiento de
        Medellín.
    </p>

<h3>Construcción del Indicador</h3>
    <p>
        Las tres primeras dimensiones o variables mencionadas, “Ambientes
        Escolar”, “Rendimiento” y “Progreso”, constituyen el puntaje total (sin bonus)
        o Indicador Multidimensional de la Calidad Educativa (IMCE). Este indicador
        cuantitativo está construido con base en el método estadístico de componentes
        principales lineales. Su estimación para cada institución permite clasificar y por tanto
        ordenar de mayor a menor las IE según el nivel de la calidad educativa. Considerando
        la bonificación, se obtiene un puntaje total (con bonus).
    </p>
    <p>
        Gracias a la construcción de este indicador multidimensional es posible construir un
        ranking de ciudad para las IE de acuerdo a la calidad en la prestación de su servicio
        educativo y conocer en términos generales, el estado en calidad de la institución.
        Entiéndase ranking como la clasificación u ordenamiento de mayor a menor de las
        instituciones educativas según lo obtenido en su puntaje total. Estos rankings se
        muestran en la plataforma.
    </p>
    <p>
        Es de resaltar que el indicador propuesto y estimado está inspirado en estudios
        recientes en educación, los cuales se basan en el diseño y estimación de indicadores
        multidimensionales, usando bien sea la técnica de componentes principales u otras
        técnicas estadísticas. Es el caso del Departamento de Educación de la Ciudad de New
        York en su Programa “Performance and Accountability: ProgressReport” (2006-2012),
        la Universidad EAFIT en su estudio “Pertinencia del Programa de Economía: una
        mirada desde los graduados” (2009) y El Consejo Económico y Social de la Comunidad
        de Madrid en su estudio “La Calidad de las Universidades en España: Elaboración de
        un Indicador Multivariado” (2010).
    </p>
<h3>Agrupación de instituciones educativas</h3>
    <p>
        El Sistema de Medición define unos grupos de instituciones educativas denominados
        clústeres, conformados de tal manera que las IE que se encuentran en un mismo
        grupo o clúster presentan características similares. Estas características similares
        corresponden a las condiciones socioeconómicas de la población estudiantil (estrato
        socioeconómico del hogar del estudiante, población estudiantil con computador
        e internet en casa, población asegurada en salud, etc) y a variables de entorno
        (amenities) de la institución educativa (razón de homicidios del barrio en el que se
        encuentra la IE, densidad poblacional del barrio, cobertura de servicios públicos del
        barrio, etc.).
    </p>
    <p>
        Esta agrupación de IE permite mostrar en la plataforma vía reportes, resultados en
        calidad de una institución educativa, no sólo en comparación con el resto de IE de la
        ciudad, sino también en comparación con IE con características similares, es decir,
        con su clúster. La metodología utilizada para la construcción de estos clúster, que en
        total son 9, fue la de k-medias que consiste en escoger aleatoriamente n instituciones
        educativas (donde n es el número de clústeres deseados) como centros de cada uno
        de los clúster para luego agrupar dentro de cada uno de ellos las instituciones mas
        cercanas a dichos centros. También se utilizaron otras metodologías de clúster como
        modelos jerárquicos y bi-etápico, pero se encontró que el método de k-medias era la
        más adecuadas porque arrojaba clúster más homogéneos (similares).
    </p>
    <p>
        El siguiente gráfico resume la explicación de la estimación del indicador
        multidimensional de la calidad educativa.
        <%= image_tag "d.jpg", :class => "indicador" %>
    </p>

SE/app/views/pages/home.html.erb
<div class="contenido">

     <div class="home top">
       <%= image_tag("b.jpg") %>
       <h1>¡Bienvenido!</h1>
     </div>

	 <div class="home left">

            <p>La Secretaría de Educación de Medellín y su Laboratorio de Calidad ponen a disposición de las
              Instituciones Educativas, padres de familia, estudiantes, docentes y la comunidad en general, el nuevo
              Sistema de Medición de la Calidad de las Instituciones Educativas (SIMCIE- Medellín), que se constituye
              como una herramienta en línea de seguimiento y evaluación del sistema educativo del Municipio de Medellín.
            </p>
            <p>
              El SIMCIE mide y reporta la calidad de cada una de las Instituciones Educativas de la ciudad utilizando
              diversos indicadores y en especial, un indicador multidimensional de la calidad educativa, el cual
              permite comparar cada institución con el resto de instituciones del Municipio y con sus similares en
              características socioeconómicas de sus estudiantes y de entorno.
            </p>
     </div>
     <div class="home right">
            <%= image_tag("a.jpg") %>
             <p>Mas información sobre el sistema</p>
              <ul style="margin: 0px 0px 0px 0px;" class="links">
                <li><%=link_to "Administradores", "/administradores" %></li>
                <li><%=link_to "Aliados Estratégicos", "/aliados" %></li>
                <li><%=link_to "Más acerca del Sistema de Medición de la Calidad de la Educación", "/acerca"%></li>
                <!--<li><%=link_to "Antecedentes", "#" %></li>-->
                <li><%= link_to "Indicador Multidimensional de la Calidad Educativa", "/indicador" %></li>
                <li><%= link_to "Fuentes de información del Sistema", "/fuentes" %></li>
                <li><%= link_to "Utilidad del Sistema", "/utilidad" %></li>
                <li><%=  link_to "Documento de ayuda", "/Glosario_SIMCIE.PDF",:target => "_blank"  %></li>
              </ul>
     </div>

     <div class="home bottom">
       <%= image_tag("c.jpg") %>
     </div>

</div>

SE/app/views/pages/utilidad.html.erb
<h3 style="text-align: center;">Utilidad del Sistema de Medición</h3>
  <br>
  <br>
  <p>
    En consecuencia, el SIMCIE-Medellín permite identificar las fortalezas y debilidades
    de cada institución educativa del Municipio según su ambiente escolar, su
    rendimiento y el progreso académico, facultando así y dando herramientas a las
    autoridades educativas y a las mismas instituciones para hacer los correctivos
    pertinentes en pro del mejoramiento de la calidad de la educación.
  </p>
  <p>
    La Secretaría de Educación de Medellín y su Laboratorio de Calidad Educativa le
    apuestan al desarrollo del indicador multidimensional y de la plataforma en web
    para el acceso del público en general al Sistema de Medición de la Calidad de las
    Instituciones Educativas de la Ciudad.
  </p>
  <p>
    Esto con la firme intención de monitorear la calidad de cada institución y del sistema
    educativo como tal y en este sentido, poder tomar decisiones de intervención pública.
  </p>
  <p>

    Finalmente, para el «Premio Ciudad de Medellín a la Calidad de la Educación 2012», el
    nuevo Sistema de Medición es utilizado dentro de la metodología de evaluación como
    insumo de información para la valoración cuantitativa.
  </p>
  <p>
    Lo invitamos a que socialice esta nueva herramienta de información.
  </p>